### ISSUE TITLE
Ways to disable compression

### ISSUE THREAD

**Issue by rigelk** [arthurfranca/apicache-plus#19]
I see you enabled compression by default - but is there a way to disable it globally? So far I rely on adding `'cache-control': 'no-transform'` to the headers, but is this clean? Maybe we could document this somewhere if it is clean enought, or add a toggle option.

**Comment by arthurfranca** [comment]
`'cache-control': 'no-transform'` is currently the only way to opt-out of apicache-plus compression. I could add compression-specific config options, but considered compression as caching implementation detail, as it won't slow down first response time (as apicache-plus doesn't compress what is sent to client. for that you would need `compression` lib or another similar one) but will speed up the next responses (if the client accepts the same encoding).

Out of curiosity, why do you want to disable it?
