### ISSUE TITLE
Support for concurrent requests?

### ISSUE THREAD

**Issue by steveocrypto** [arthurfranca/apicache-plus#23]
Reference: https://github.com/kwhitley/apicache/issues/33

Having an issue with the original library not handling concurrent requests.  Is this supported in apicache-plus?

**Comment by arthurfranca** [comment]
Revisiting it i see that the "2." part is how it *probably should* behave for GET requests (so to not wait for e.g. a full video download), but it isn't right now. At the moment, all concurrent requests will [wait](https://github.com/arthurfranca/apicache-plus/blob/774ef5f6ee20189bec653ed8637cc50b6dc34dd8/src/apicache.js#L1307-L1310) for the first request that acquired a lock to finish caching/responding. So it will be delayed till the first one sends response, exactly what kwhitley/apicache#33 and @steveocrypto wanted.
