### ISSUE TITLE
Decompression failed error with  node-redis when serving cached response

### ISSUE THREAD

**Issue by masterpandabear** [arthurfranca/apicache-plus#27]
Hello, I am getting an error when trying out the middleware.

I recently tried to switch apicache with this fork. As I understand, it has the same API but whenever the middleware tries to respond with cached response I get a `Decompression failed` in postman and requests send using axios just fail with no error code.

```
const apiCache = require('apicache-plus')

const redisClient = redis.createClient(getRedisConfiguration({ detect_buffers: true })) // this gets node-redis v3 client 
const redisApiCache = apiCache.options({
  redisClient,
  include: [200, 201]
})

```

Redis shows the cached call along with another entry that seems to hold the compressed response.
Any help will be much appreciated.

**Comment by arthurfranca** [comment]
Are you using v2.2.3 already (`npm list apicache-plus`)? Cause there was a bug that may cause this on older versions of apicache-plus.

If you are already using v2.2.3, try using ioredis instead and check if the problem persists.

**Comment by masterpandabear** [comment]
I am using apicache-plus@2.2.3, so far I have it running without compression, by using the 'no-transform' value in the cache-control header. 

I could try ioredis, to see if the problem is there and let you know.

EDIT: It seems to be working fine with ioredis, does this mean that this library is no longer compatible with node-redis? I do want to eventually move to ioredis, but other parts of the application still depend on node-redis

**Comment by arthurfranca** [comment]
node-redis may work but it is not guaranteed. I've migrated to ioredis myself. Unfortunately, node-redis and ioredis aren't fully interchangeable anymore, specially node-redis v4+ that now considers the ioredis-like method signatures as legacy mode.

**Comment by masterpandabear** [comment]
Got it, thank you for your time. Turning off compression with node-redis seems to be working fine, as we migrate to ioredis I will turn it back on.
